"""Themen, Symbole (16x16-Pixel-Sprites als ASCII) und Sprüche der Space-Slotmaschine.

Jedes Thema hat sieben Symbole; das letzte ist das Jackpot-Symbol. Die Sprites sind eigene
Zeichnungen, Buchstaben stehen für Farben aus PALETTE, '.' ist durchsichtig.
"""
from __future__ import annotations

PALETTE = {
    "w": (245, 245, 250), "k": (18, 16, 22), "d": (70, 70, 80), "s": (160, 165, 180),
    "r": (235, 40, 40), "o": (255, 140, 30), "y": (255, 220, 60), "g": (70, 220, 90),
    "l": (170, 255, 90), "c": (80, 230, 255), "b": (50, 110, 255), "v": (140, 70, 230),
    "m": (255, 70, 200), "p": (255, 150, 200), "n": (140, 90, 40), "t": (230, 190, 150),
    "e": (120, 60, 20), "a": (35, 90, 45), "u": (110, 130, 160), "h": (90, 20, 20),
}

# ---- Symbole ------------------------------------------------------------------------------
ALIEN = """
................
.....gggggg.....
....gggggggg....
...gggggggggg...
...gggggggggg...
...gkkkggkkkg...
...gkwkggkwkg...
...gkkkggkkkg...
...gggggggggg...
....gggggggg....
.....gggggg.....
......gggg......
......gggg......
.....ggkkgg.....
.....gggggg.....
................
"""
DRINK = """
................
....ssssssss....
...s........s...
...s.cccccc.s...
...s.cccccc.s...
...s.cwcccc.s...
...s.cccccc.s...
....sccccccs....
.....scccss.....
......sccs......
.......ss.......
.......ss.......
.......ss.......
.....ssssss.....
....ssssssss....
................
"""
BLASTER = """
................
................
..dddddddddd....
.ddddddddddddd..
.dsssssssssddd..
.ddddddddddddd..
......dddd..rr..
......dddd...r..
......ddd.......
......ddd.......
......ddd.......
.....dddd.......
.....ddd........
................
................
................
"""
WUERFEL = """
................
...wwwwwwwwww...
..wwwwwwwwwwww..
..wwkkwwwwwwww..
..wwkkwwwwkkww..
..wwwwwwwwkkww..
..wwwwwwwwwwww..
..wwwwwkkwwwww..
..wwwwwkkwwwww..
..wwwwwwwwwwww..
..wwkkwwwwwwww..
..wwkkwwwwkkww..
..wwwwwwwwkkww..
..wwwwwwwwwwww..
...wwwwwwwwww...
................
"""
CREDITS = """
................
.....yyyyyy.....
...yyyyyyyyyy...
..yyyooooooyyy..
..yyoyyyyyyoyy..
..yyoyykkyyoyy..
..yyoyyykyyoyy..
..yyoyykkyyoyy..
..yyoyykkyyoyy..
..yyoyyyyyyoyy..
..yyyooooooyyy..
...yyyyyyyyyy...
.....yyyyyy.....
..ssssssssssss..
..ssssssssssss..
................
"""
DROIDE = """
................
......ssss......
.....ssssss.....
....sscssrss....
....ssssssss....
....ssssssss....
...ssssssssss...
..ssuuuuuuuuss..
..ssussrrssuss..
..ssuuuuuuuuss..
..ssussssssuss..
..ssuuuuuuuuss..
...ssssssssss...
....ssssssss....
.....sdddds.....
................
"""
KUSS = """
................
................
................
....rr....rr....
...rrrr..rrrr...
..rrrrrrrrrrrr..
.rrrrrrrrrrrrrr.
.rrrrrrrrrrrrrr.
..rrhhhhhhhhrr..
..rrrrrrrrrrrr..
...rrrrrrrrrr...
....rrrrrrrr....
.....rrrrrr.....
......rrrr......
................
................
"""
HELM = """
................
.....kkkkkk.....
....kkkkkkkk....
...kkkkkkkkkk...
..kkkkkkkkkkkk..
..kkkkkkkkkkkk..
..kkddkkkkddkk..
..kkddkkkkddkk..
..kkkkkkkkkkkk..
..kkkkkddkkkkk..
..kkkkkkkkkkkk..
..kkksssssskkk..
..kkksksskskkk..
...kkkkkkkkkk...
....kkkkkkkk....
................
"""
SCHWERT = """
................
..............r.
.............rr.
............rr..
...........rr...
..........rr....
.........rr.....
........rr......
.......rr.......
......rr........
.....ss.........
....ss..........
...ss...........
..dd............
.dd.............
................
"""
STATION = """
................
.....ssssss.....
...ssssssssss...
..sssdddssssss..
..ssdkkkdsssss..
.sssdkkkdssssss.
.ssssdddsssssss.
.sssssssssssss..
.ddddddddddddd..
.sssssssssssss..
.sssssssssssss..
..ssssssssssss..
..ssssssssssss..
...ssssssssss...
.....ssssss.....
................
"""
LAEUFER = """
................
................
....ssssssss....
...ssssssssss...
..sssdddssssss..
..sssssssssssss.
...sssssssss....
....ss.ss.ss....
....ss.ss.ss....
...ss..ss..ss...
...ss..ss..ss...
..ss...ss...ss..
..ss...ss...ss..
.ss....ss....ss.
.dd....dd....dd.
................
"""
JAEGER = """
................
.dd..........dd.
.dd..........dd.
.dd..........dd.
.dd...ssss...dd.
.dd..ssssss..dd.
.dddsssrrsssddd.
.dddsssrrsssddd.
.dd..ssssss..dd.
.dd...ssss...dd.
.dd..........dd.
.dd..........dd.
.dd..........dd.
................
................
................
"""
BLITZ = """
................
....c......c....
...c.c....c.c...
..c...c..c...c..
.......cc.......
......c..c......
.....c....c.....
....tttttttt....
...tttttttttt...
...tttttttttt...
...tttttttttt...
....tttttttt....
.....kkkkkk.....
.....kkkkkk.....
.....kkkkkk.....
................
"""
TOTENKOPF = """
................
.....wwwwww.....
....wwwwwwww....
...wwwwwwwwww...
...wwwwwwwwww...
...wkkkwwkkkw...
...wkkkwwkkkw...
...wwwwkkwwww...
...wwwwwwwwww...
....wwwwwwww....
.....wkwkwk.....
.....wwwwww.....
................
................
................
................
"""
DROIDENKOPF = """
................
.....uuuuuu.....
....uuuuuuuu....
...uuuuuuuuuu...
...uurruuuuuu...
...uurruuuuuu...
...uuuuuuuuuu...
..uuuuuuuuuuuu..
..uuuuuuuuuuuu..
...uuuuuuuuuu...
....uuuuuuuu....
....ssss.ss.....
....sss.........
....ss..........
................
................
"""
ZAHNRAD = """
................
......s..s......
....sssssssss...
...ssssssssss...
..s.ssssssss.s..
..ssss....ssss..
..sss......sss..
.ssss......ssss.
.ssss......ssss.
..sss......sss..
..ssss....ssss..
..s.ssssssss.s..
...ssssssssss...
....sssssssss...
......s..s......
................
"""
TRIEBWERK = """
................
...dddddddddd...
..dddddddddddd..
..ddssssssssdd..
..ddssssssssdd..
..dddddddddddd..
...dddddddddd...
....dddddddd....
.....oooooo.....
....oooooooo....
....ooyyyyoo....
.....oyyyyo.....
......oyyo......
.......oo.......
................
................
"""
SCHLUESSEL = """
................
..ss............
.ssss...........
.ss.ss..........
.ss..ss.........
..ss..ss........
...ss..ss.......
....ss..ss......
.....ss..ss.....
......ss..ss....
.......ss..ss...
........ss..ss..
.........ss.sss.
..........sssss.
...........sss..
................
"""
BATTERIE = """
................
......ssss......
.....ssssss.....
....gggggggg....
....gggggggg....
....gggggggg....
....gggggggg....
....ggykkygg....
....ggkyykgg....
....gggggggg....
....gggggggg....
....gggggggg....
....gggggggg....
....gggggggg....
................
................
"""
KRABBLER = """
................
................
..r..........r..
...r........r...
....rrrrrrrr....
...rrrrrrrrrr...
.rrrrkkrrkkrrrr.
..rrrrrrrrrrrr..
.r.rrrrrrrrrr.r.
...rrrrrrrrrr...
.r..rrrrrrrr..r.
.....rrrrrr.....
...r........r...
..r..........r..
................
................
"""
SCHAEDEL = """
................
..tt........tt..
..tttt....tttt..
...tttttttttt...
...tttttttttt...
..tttttttttttt..
..ttkkkttkkktt..
..ttkkkttkkktt..
..tttttttttttt..
...ttttkkttt....
....tttttttt....
.....tktktk.....
.....tttttt.....
................
................
................
"""
BALL = """
................
.....wwwwww.....
....wwwwwwww....
...wwswwswwsw...
..wswwswwswwsw..
..wwswwswwswww..
..wswwswwswwsw..
..wwswwswwswww..
..wswwswwswwsw..
..wwswwswwswww..
..wswwswwswwsw..
...wwswwswwsw...
....wwwwwwww....
.....wwwwww.....
................
................
"""
FAHNE = """
................
......ss........
......ssrrrrr...
......ssrrrrrr..
......ssrrrrrrr.
......ssrrrrrr..
......ssrrrrr...
......ss........
......ss........
......ss........
......ss........
......ss........
..aaaaaaaaaaaa..
.aaaaaakkaaaaaa.
.aaaaaaaaaaaaaa.
................
"""
CART = """
................
................
....wwwwwwww....
...wwwwwwwwww...
...ww......ww...
...ww......ww...
...wwwwwwwwww...
...wwwwwwwwww...
..wwwwwwwwwwww..
..wwwwwwwwwwww..
..wwwwwwwwwwww..
..wwkkwwwwkkww..
..wkkkkwwkkkkw..
...kkkk..kkkk...
....kk....kk....
................
"""
BIER = """
................
....wwwwwww.....
...wwwwwwwww....
...wwwwwwwwww...
...yyyyyyyyyss..
...yyyyyyyyy.s..
...yyyyyyyyy.s..
...yyyyyyyyyss..
...yyyyyyyyy....
...yyyyyyyyy....
...yyyyyyyyy....
...yyyyyyyyy....
...yyyyyyyyy....
...sssssssss....
................
................
"""
SCHLAEGER = """
................
..............s.
.............ss.
............ss..
...........ss...
..........ss....
.........ss.....
........ss......
.......ss.......
......ss........
.....ss.........
....ss..........
...dd...........
.dddd...........
.ddd............
................
"""
KRATER = """
................
................
................
................
....dddddddd....
...dddddddddd...
..dddddddddddd..
.dddddddddddddd.
.ddtttttttttttd.
..dtttttttttttd.
..ddtttttttttd..
...ddtttttttd...
....ddddddddd...
................
................
................
"""
POKAL = """
................
..yyyyyyyyyyyy..
..yyyyyyyyyyyy..
.yyyyyyyyyyyyyy.
.y.yyyyyyyyyy.y.
.y.yyyyyyyyyy.y.
..y.yyyyyyyy.y..
.....yyyyyy.....
......yyyy......
.......yy.......
.......yy.......
......yyyy......
.....yyyyyy.....
....yyyyyyyy....
....yyyyyyyy....
................
"""
KISTE = """
................
..nnnnnnnnnnnn..
..neeeeeeeeeen..
..nennnnnnnnen..
..nennnnnnnnen..
..neeeeeeeeeen..
..nnnnnnnnnnnn..
..nennnnnnnnen..
..nennmmmmnnen..
..nennmmmmnnen..
..nennnnnnnnen..
..nnnnnnnnnnnn..
..neeeeeeeeeen..
..nnnnnnnnnnnn..
................
................
"""
HANDSCHELLEN = """
................
................
...sss....sss...
..s...s..s...s..
.s.....ss.....s.
.s.....ss.....s.
.s.....ss.....s.
..s...s..s...s..
..sssssssssssss.
..s...s..s...s..
.s.....ss.....s.
.s.....ss.....s.
.s.....ss.....s.
..s...s..s...s..
...sss....sss...
................
"""
PLAKAT = """
................
.tttttttttttttt.
.tkkkkkkkkkkkkt.
.tttttttttttttt.
.ttttttkkkttttt.
.tttttkkkkkkttt.
.tttttkttktkttt.
.tttttkkkkkkttt.
.tttttktkkktttt.
.ttttttkkkktttt.
.tttttttttttttt.
.trrrrrrrrrrrrt.
.tttttttttttttt.
.tkkkkkkkkkkkkt.
.tttttttttttttt.
................
"""
FRACHTER = """
................
................
.......sss......
......sssss.....
.....sssssss....
....sssdddsss...
...sssddddddss..
..sssdddddddsss.
.ssssssssssssss.
..ssssssssssss..
...sssooosss....
....ssooss......
.....oooo.......
......oo........
................
................
"""
BARREN = """
................
................
................
....yyyyyy......
...yyyyyyyy.....
..yyyyyyyyyy....
.....yyyyyy.yy..
....yyyyyyyyyyy.
...yyyyyyyyyyy..
..yyyyyyyyyyyy..
.......yyyyyy...
......yyyyyyyy..
.....yyyyyyyyyy.
................
................
................
"""
KARTE = """
................
.tttttttttttttt.
.tttttttttttttt.
.ttbbbbbtttttbt.
.tbbbbbbbttttbt.
.tbbbbbbbbtttbt.
.ttbbbbbbbbtttt.
.tttbbbbbbttttt.
.ttttbbbbtttttt.
.tttttbbttrrttt.
.ttttttttrrrrtt.
.ttttttttttrttt.
.tttttttttttttt.
.tttttttttttttt.
................
................
"""
SACK = """
................
.......yy.......
......y..y......
......yyyy......
.....nnnnnn.....
....nnnnnnnn....
...nnnnnnnnnn...
..nnnnnnnnnnnn..
..nnnyyyyyynnn..
..nnnnykkynnnn..
..nnnnyykynnnn..
..nnnnykkynnnn..
..nnnyyyyyynnn..
...nnnnnnnnnn...
....nnnnnnnn....
................
"""
RAKETE = """
................
.......ww.......
......wwww......
......wrrw......
.....wwwwww.....
.....wwwwww.....
.....wwccww.....
.....wwccww.....
.....wwwwww.....
....rwwwwwwr....
...rrwwwwwwrr...
..rrrwwwwwwrrr..
..rrr.oooo.rrr..
......oyyo......
.......oo.......
................
"""
UFO = """
................
................
......cccc......
.....cccccc.....
.....cwcccc.....
..ssssssssssss..
.ssssssssssssss.
ssssssssssssssss
.sysysysysysysy.
..ssssssssssss..
....s..s..s.....
...y...y...y....
................
................
................
................
"""
STRAHLER = """
................
................
....cccccccc....
...cccccccccc...
..cccccccccccc..
..ccccccccccc...
...ccccccccc....
......cccc......
......cccc......
.....ccccc......
.....cccc.......
.....ccc........
....cccc........
....ccc.........
................
................
"""
ROBOTER = """
................
.......ss.......
.....ssssss.....
....ssssssss....
....scssscss....
....ssssssss....
....ssrrrrss....
.....ssssss.....
..ssssssssssss..
..ssssssssssss..
..s.ssyyyyss.s..
..s.ssssssss.s..
....ssssssss....
....sss..sss....
....sss..sss....
................
"""
PLANET = """
................
................
......vvvv......
.....vvvvvv.....
....vvvvmvvv....
...vvvmmmmvvvo..
..ovvvmmmmvvo...
.ooovvvvvvvooo..
..ooooooooooo...
...ovvvvvvvvo...
....vvvvvvvv....
.....vvvvvv.....
......vvvv......
................
................
................
"""
ASTRONAUT = """
................
.....wwwwww.....
....wwwwwwww....
....wkkkkkkw....
....wkkccckw....
....wkkkkkkw....
.....wwwwww.....
...wwwwwwwwww...
..wwwwwrrwwwww..
..ww.wwwwww.ww..
..ww.wwwwww.ww..
.....wwwwww.....
.....ww..ww.....
.....ww..ww.....
.....dd..dd.....
................
"""
MOND = """
................
......ssss......
....ssssssss....
...sssssdsssss..
..ssssssssssss..
..sssdssssssss..
.ssssssssssdsss.
.sssssssdsssssss
.ssssssssssssss.
.sssdssssssssss.
..ssssssssdsss..
..ssssssssssss..
...sssdsssssss..
....ssssssss....
......ssss......
................
"""

# ---- Themen -------------------------------------------------------------------------------
# colors: (a, b) = zwei Grundfarben des Themas für Rahmen und Hintergrund, 0..1
THEMES = [
    {
        "name": "KANTINE", "title": "KANTINE AM RAND DER GALAXIS", "subtitle": "WIR BEDIENEN KEINE DROIDEN. AUSNAHMEN GEGEN AUFPREIS.",
        "colors": ((0.95, 0.45, 0.10), (0.30, 0.90, 0.40)),
        "symbols": [("ALIEN", ALIEN), ("DRINK", DRINK), ("BLASTER", BLASTER), ("WUERFEL", WUERFEL),
                    ("CREDITS", CREDITS), ("DROIDE", DROIDE), ("KUSS", KUSS)],
        "lose": ["Die Bank gewinnt. Immer. Das ist der Trick.", "Noch ein Drink? Der Verlust ist derselbe.",
                 "Der Wirt lacht. Er hat gut lachen.", "Verloren. Die Band spielt trotzdem weiter."],
        "near": ["So knapp. Wie dein Kontostand.", "Fast. Die Kantine kennt kein Fast.", "Zwei von drei. Der Wirt nickt mitleidig."],
        "small": ["Kleiner Gewinn. Reicht für ein Glas Wasser.", "Gewonnen. Der Wirt schaut misstrauisch."],
        "big": ["Drei gleiche. Die Kantine wird still.", "Gewinn. Jemand zieht den Blaster. Nur so."],
        "jackpot": ["KUSS KUSS KUSS. Der Abend ist gerettet.", "Jackpot. Die Band spielt dein Lied."],
    },
    {
        "name": "IMPERIUM", "title": "IMPERIALES GLUECKSSPIEL", "subtitle": "WIDERSTAND IST ZWECKLOS. VERLIEREN AUCH.",
        "colors": ((0.85, 0.10, 0.10), (0.25, 0.25, 0.35)),
        "symbols": [("HELM", HELM), ("SCHWERT", SCHWERT), ("STATION", STATION), ("LAEUFER", LAEUFER),
                    ("JAEGER", JAEGER), ("BLITZ", BLITZ), ("TOTENKOPF", TOTENKOPF)],
        "lose": ["Das Imperium dankt für die Spende.", "Verloren. Dein Glaube enttäuscht mich.",
                 "Die dunkle Seite nimmt auch Kleingeld.", "Ein Verlust. Wie befohlen."],
        "near": ["Fast. Der Imperator ist nicht amüsiert.", "Zwei Treffer. Die Flotte wartet auf den dritten.", "Knapp daneben. Das kostet einen Offizier."],
        "small": ["Kleiner Gewinn. Der Imperator gestattet es.", "Gewonnen. Vorerst."],
        "big": ["Drei gleiche. Die Flotte salutiert.", "Gewinn. Das war kein Zufall. Das war Macht."],
        "jackpot": ["TOTENKOPF dreifach. Die Galaxis gehört dir. Heute.", "Jackpot. Der Thron ist frei."],
    },
    {
        "name": "SCHROTTPLATZ", "title": "SCHROTTPLATZ DER AEUSSEREN WELTEN", "subtitle": "ALLES GEBRAUCHT. ALLES KAPUTT. ALLES TEUER.",
        "colors": ((0.80, 0.55, 0.15), (0.35, 0.45, 0.55)),
        "symbols": [("DROIDENKOPF", DROIDENKOPF), ("ZAHNRAD", ZAHNRAD), ("TRIEBWERK", TRIEBWERK), ("SCHLUESSEL", SCHLUESSEL),
                    ("BATTERIE", BATTERIE), ("KRABBLER", KRABBLER), ("SCHAEDEL", SCHAEDEL)],
        "lose": ["Verloren. Der Händler zeigt seine drei Zähne.", "Nichts. Wie die Garantie hier.",
                 "Verlust. Die Krabbler freuen sich.", "Rost gewinnt. Rost gewinnt immer."],
        "near": ["Fast. Ein Zahnrad hat gefehlt.", "Zwei Teile. Das dritte liegt irgendwo im Sand.", "Knapp. Der Händler hat dich gesehen."],
        "small": ["Kleiner Gewinn. Ein halbes Triebwerk.", "Gewonnen. Es ist nur leicht verbogen."],
        "big": ["Drei gleiche. Das Ding fliegt vielleicht sogar.", "Gewinn. Der Händler weint."],
        "jackpot": ["SCHAEDEL dreifach. Der Platz gehört dir. Inklusive Krabbler.", "Jackpot. Die Batterie ist sogar voll."],
    },
    {
        "name": "ORBITGOLF", "title": "ORBIT-GOLF CLUB", "subtitle": "LOCH 19. SCHWERKRAFT OPTIONAL.",
        "colors": ((0.20, 0.75, 0.35), (0.95, 0.90, 0.80)),
        "symbols": [("BALL", BALL), ("FAHNE", FAHNE), ("CART", CART), ("BIER", BIER),
                    ("SCHLAEGER", SCHLAEGER), ("KRATER", KRATER), ("POKAL", POKAL)],
        "lose": ["Verloren. Wie dein Ball im Krater.", "Bogey. Der Cart fährt trotzdem weiter.",
                 "Nichts. Das Clubhaus nimmt Kreditkarten.", "Verlust. Der Caddy sagt nichts. Wie immer."],
        "near": ["Fast. Lippe des Lochs, kein Einlochen.", "Zwei Treffer. Der Putt war zu kurz.", "Knapp. Der Wind hat geschoben. Angeblich."],
        "small": ["Par. Reicht für ein Bier.", "Gewonnen. Der Caddy hebt eine Augenbraue."],
        "big": ["Birdie dreifach. Das Clubhaus applaudiert.", "Gewinn. Der Ball liegt im Loch. Wirklich."],
        "jackpot": ["POKAL POKAL POKAL. Hole-in-one im Orbit.", "Jackpot. Der Cart bekommt Flügel."],
    },
    {
        "name": "SCHMUGGLER", "title": "SCHMUGGLERKASINO", "subtitle": "KEINE FRAGEN. KEINE QUITTUNGEN. KEINE GNADE.",
        "colors": ((0.95, 0.75, 0.20), (0.45, 0.20, 0.55)),
        "symbols": [("KISTE", KISTE), ("HANDSCHELLEN", HANDSCHELLEN), ("PLAKAT", PLAKAT), ("FRACHTER", FRACHTER),
                    ("BARREN", BARREN), ("KARTE", KARTE), ("SACK", SACK)],
        "lose": ["Verloren. Die Fracht war sowieso nicht deine.", "Nichts. Die Handschellen passen übrigens.",
                 "Verlust. Das Kopfgeld steigt.", "Die Bank gewinnt. Die Bank sind wir."],
        "near": ["Fast. Der Zoll hat die dritte Kiste.", "Zwei Treffer. Der Frachter springt ohne dich.", "Knapp. Das Plakat zeigt dein Gesicht."],
        "small": ["Kleiner Gewinn. Schnell einstecken.", "Gewonnen. Niemand hat es gesehen."],
        "big": ["Drei gleiche. Der Frachter ist bezahlt.", "Gewinn. Die Karte führt wohl doch wohin."],
        "jackpot": ["SACK dreifach. Das Kopfgeld zahlst du selbst.", "Jackpot. Hyperantrieb an, Fragen aus."],
    },
    {
        "name": "RETRO", "title": "RAUMFAHRT-RETRO-AUTOMAT", "subtitle": "SEIT 1957 IN BETRIEB. UNGEFAEHR.",
        "colors": ((0.35, 0.80, 1.00), (0.95, 0.35, 0.60)),
        "symbols": [("RAKETE", RAKETE), ("UFO", UFO), ("STRAHLER", STRAHLER), ("ROBOTER", ROBOTER),
                    ("PLANET", PLANET), ("MOND", MOND), ("ASTRONAUT", ASTRONAUT)],
        "lose": ["Verloren. Der Mond nimmt es dir nicht übel.", "Nichts. Der Roboter zuckt mit den Schultern.",
                 "Verlust. Das UFO fliegt weiter.", "Kein Gewinn. Der Countdown war umsonst."],
        "near": ["Fast. Die Rakete stand schon auf der Rampe.", "Zwei Treffer. Der dritte kreist noch.", "Knapp. Der Astronaut winkt trotzdem."],
        "small": ["Kleiner Gewinn. Ein Mondstein.", "Gewonnen. Der Roboter piept anerkennend."],
        "big": ["Drei gleiche. Zündung. Abheben.", "Gewinn. Die Umlaufbahn ist erreicht."],
        "jackpot": ["ASTRONAUT dreifach. Ein großer Schritt für dein Konto.", "Jackpot. Das UFO nimmt dich mit."],
    },
]
